### ISSUE TITLE
Custom OIDC provider not working on Android

### ISSUE THREAD

**Issue by ObeA** [aws-amplify/amplify-flutter#1022]
**Describe the bug**
I'm trying to get a custom OIDC provider to work with the Amplify GraphQL API based on [this guide](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#oidc). On iOS it works, but on Android I keep getting the message "[REST OIDC/Lambda is not supported yet](https://github.com/aws-amplify/amplify-flutter/blob/75264e817a2d5aba97979443541106bacb475a6b/packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/auth/FlutterAuthProvider.kt#L73)" followed by the error below. `getLatestAuthToken` on my implementation of `OIDCAuthProvider` is never called on Android.

```
E/FlutterAuthProviders( 6782): REST OIDC/Lambda is not supported yet.
E/amplify:flutter:api( 6782): GraphQL mutate operation failed
E/amplify:flutter:api( 6782): ApiException{message=OkHttp client failed to make a successful request., cause=ApiAuthException{message=Failed to retrieve auth token from OIDC provider., cause=ApiAuthException{message=Unable to retrieve token for OPENID_CONNECT, cause=null, recoverySuggestion=Make sure you register your auth providers in the addPlugin call and
E/amplify:flutter:api( 6782): that getLatestAuthToken returns a value.}, recoverySuggestion=Check the application logs for details.}, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
E/amplify:flutter:api( 6782): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation.start(AppSyncGraphQLOperation.java:113)
E/amplify:flutter:api( 6782): 	at com.amplifyframework.api.aws.AWSApiPlugin.query(AWSApiPlugin.java:231)
E/amplify:flutter:api( 6782): 	at com.amplifyframework.api.aws.AWSApiPlugin.query(AWSApiPlugin.java:218)
E/amplify:flutter:api( 6782): 	at com.amplifyframework.api.ApiCategory.query(ApiCategory.java:51)
E/amplify:flutter:api( 6782): 	at com.amazonaws.amplify.amplify_api.FlutterGraphQLApi$Companion.query(FlutterGraphQLApi.kt:97)
E/amplify:flutter:api( 6782): 	at com.amazonaws.amplify.amplify_api.AmplifyApiPlugin.onMethodCall(AmplifyApiPlugin.kt:101)
E/amplify:flutter:api( 6782): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/amplify:flutter:api( 6782): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/amplify:flutter:api( 6782): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/amplify:flutter:api( 6782): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/amplify:flutter:api( 6782): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/amplify:flutter:api( 6782): 	at android.os.Looper.loop(Looper.java:183)
E/amplify:flutter:api( 6782): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/amplify:flutter:api( 6782): 	at java.lang.reflect.Method.invoke(Native Method)
E/amplify:flutter:api( 6782): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/amplify:flutter:api( 6782): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/amplify:flutter:api( 6782): Caused by: ApiAuthException{message=Failed to retrieve auth token from OIDC provider., cause=ApiAuthException{message=Unable to retrieve token for OPENID_CONNECT, cause=null, recoverySuggestion=Make sure you register your auth providers in the addPlugin call and
```

**To Reproduce**
Based on the [Getting started](https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/) and [this guide](https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/flutter/#oidc) I created [this repo](https://github.com/ObeA/amplify-flutter-custom-oidc) with a minimal setup to reproduce the issue.

Custom OIDC auth provider:
```dart
class CustomOIDCProvider extends OIDCAuthProvider {
  const CustomOIDCProvider();

  @override
  Future<String?> getLatestAuthToken() async {
    // This is never called on Android
    return 'some token';
  }
}
```

Configuration:
```dart
void _configureAmplify() async {
  // Add the following line to add API plugin to your app
  Amplify.addPlugin(AmplifyAPI(authProviders: const [CustomOIDCProvider()]));

  try {
    await Amplify.configure(amplifyconfig);
  } on AmplifyAlreadyConfiguredException {
    print(
        "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
  }
}
```

**Expected behavior**
`getLatestAuthToken` on my `OIDCAuthProvider` should be called on Android.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- [x] Android
- [ ] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.5.3, on Manjaro Linux 5.13.19-2-MANJARO, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/obe/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/obe/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/obe/Android/Sdk
    • Java binary at: /home/obe/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/obe/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_api:
    dependency: "direct main"
    description:
      name: amplify_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_core:
    dependency: transitive
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.6"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.1"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  date_time_format:
    dependency: transitive
    description:
      name: date_time_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.4"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.10"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.5"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
sdks:
  dart: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

  ```

</details>
