### ISSUE TITLE
Flutter app Crashes with AmplifyAPI() configured

### ISSUE THREAD

**Issue by Freemanlabs** [aws-amplify/amplify-flutter#1048]
**Describe the bug**
With AmplifyAPI() in my flutter app configuration, my app crashes on start in release mode. When I take it out, my build release works fine. How do I solve this (big) issue?

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- [x] Android
- [ ] iOS

**pubspec.yml**
```
dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.3.8
  google_fonts: ^2.1.0
  fl_chart: ^0.40.2
  iso_countries: ^2.1.0
  amplify_flutter: ^0.2.6
  amplify_auth_cognito: ^0.2.6
  amplify_datastore: ^0.2.6
  amplify_api: ^0.2.6
  amplify_analytics_pinpoint: ^0.2.6
```
