### ISSUE TITLE
Login / Signup issues affecting some android devices.

### ISSUE THREAD

**Issue by devon2018** [aws-amplify/amplify-flutter#1205]
**Describe the bug**
There seems to be a login issue using the signIn or signUp methods on android devices. But its strange as its not affecting all devices and i'm not getting any good errors to work with, this issue does seem to only affect older / less common devices but I've not seen any commonalities. 

The error i'm getting is always the same and is this

```
E/amplify:flutter:auth_cognito(11609): AuthException
I/flutter (11609): Sign in failed

```
Sign in code looks like this:

```
  SignInResult res = await Amplify.Auth.signIn(username: form['email'], password: form['password']);
```
I've tested on the following devices: 
Galaxy S10 (Android 11)- Works as expected
Galaxy A9(2017) (Android 10)- Works as expected
Galaxy S7 Edge (Android V9)- Works as expected
Galaxy J3 2017 (Android 9) - Throws error
OnePlus 5T (Android 10)- Throws error
Huawei Y6 2019 (Android 9)- Throws error

**To Reproduce**

**Expected behavior**
Login/Signup to work as expected

**Screenshots**

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[x] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/devonray/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/devonray/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • SM J330FN (mobile) • 4200ffa6e06db4f1 • android-arm    • Android 9 (API 28)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 96.0.4664.93

```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  name: appname
  description: A new Flutter project.
  publish_to: "none"
  version: 1.0.0+1
  environment:
    sdk: ">=2.12.0 <3.0.0"
  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.2
    get_it: ^7.2.0
    fluttericon: ^2.0.0
    flutter_form_builder: ^7.0.0
    form_builder_validators: ^7.2.0
    pin_code_fields: ^7.3.0
    pull_to_refresh: ^2.0.0
    sliding_up_panel: ^2.0.0+1
    carousel_slider: ^4.0.0
    amplify_core: ^0.2.6
    amplify_flutter: ^0.2.6
    amplify_auth_cognito: ^0.2.6
    http: ^0.13.4
    redux: ^5.0.0
    redux_thunk: ^0.4.0
    flutter_redux: ^0.8.2
    form_builder_image_picker: ^2.0.0
    image_picker: ^0.8.4+4
    image: ^3.0.8
    package_info_plus: ^1.3.0
    flutter_typeahead: ^3.2.3
    url_launcher: ^6.0.15
    purchases_flutter: ^3.8.0
  dev_dependencies:
    flutter_launcher_icons: ^0.9.2
    flutter_test:
      sdk: flutter
  flutter:
    uses-material-design: true
    assets:
      - assets/images/logo.png
      - assets/images/icon.png
      - assets/images/slide_1.png
      - assets/images/slide_2.png
      - assets/images/slide_3.png
  
  flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/icon.png"
    remove_alpha_ios: true

  ```

</details>

**Smartphone (please complete the following information):**
see above

**Additional context**
