### ISSUE TITLE
Could not configure Amplify: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully.

### ISSUE THREAD

**Issue by aqarcoSys** [aws-amplify/amplify-flutter#1237]
**Describe the bug**
Amplify configuration not working with hot reload, when I change the code the exception is raided Amplify plugin XXXX was not added  successfully

```dart
  Future<void> _configure() async {
    try {
      
      kLogger.i("configuring Amplify", "[AmplifyService]");

      // add Amplify plugins
      await Amplify.addPlugins([
        AmplifyAuthCognito(),
        _dataStorePlugin,
        AmplifyAPI(),
        // _pinpointPlugin,
        // _storageS3Plugin
      ]);

      kLogger.i("Plugins added", "[AmplifyService]");

      if (!Amplify.isConfigured) await Amplify.configure(amplifyconfig);

    } on AmplifyAlreadyConfiguredException {

      kLogger.w("Amplify already configured !");

    } catch (e) {

      kLogger.e(e.toString(), "[AmplifyService][_configure]");
    }
  }
```

**To Reproduce**

**Expected behavior**
Amplify configure  should .work with hot reload, not with reinstall the app

**Platform**
Amplify Flutter currently supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**pubspec.yml**

```yml
  #amplify
  amplify_flutter: ^0.2.10
  amplify_datastore: ^0.2.10
  amplify_api: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_analytics_pinpoint: ^0.2.10
  amplify_storage_s3: ^0.2.10
```

**flutter doctor**
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```
