### ISSUE TITLE
The operation couldn’t be completed. (Amplify.AuthError error 5.)

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#1368]
When I try to login in iOS am getting the following error. But the user is exist. The same user it's working in android.
Tried with simulator and emulator. After changing the plugin version started getting like this kind of behaviour.

`amplify_flutter: ^0.3.2
  amplify_auth_cognito: ^0.3.2`

```2022-02-17 10:04:44.317551+0530 Runner[12839:1103436] [AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 1.)
2022-02-17 10:04:44.319889+0530 Runner[12839:1103455] flutter: UserNotFoundException(message: User does not exist., recoverySuggestion: Make sure that the user is present in the backend, underlyingException: The operation couldn’t be completed. (AmplifyPlugins.AWSCognitoAuthError error 0.))
2022-02-17 10:04:44.322924+0530 Runner[12839:1103436] [AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 5.)
```

AmplifyConfig File:

```
const amplifyConfigQA = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "xxxxxx",
                            "Region": "xxxxxx"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxxx",
                        "AppClientId": "xxxxxx",
                        "Region": "xxxxxx"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxx",
                            "AppClientId": "xxxxxx",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}''';
````

**Comment by haverchuck** [comment]
@Sunsiha I have been unable to reproduce this. Can you please post the exact amplify-flutter version(s) from your `pubspec.lock` file, as well as the code you are using to call signIn? Are you doing any custom validation on the email address or using any lambda triggers?

**Comment by Sunsiha** [comment]
@haverchuck Using lambda triggers. 
`Feb 21 03:56:56 Runner(Amplify)[799] <Error>: <private>
Feb 21 03:56:56 Runner(Flutter)[799] <Notice>: flutter: UserNotFoundException(message: User does not exist., recoverySuggestion: Make sure that the user is present in the backend, underlyingException: The operation couldn\M-b\M^@\M^Yt be completed. (AmplifyPlugins.AWSCognitoAuthError error 0.))
Feb 21 03:56:56 Runner(Amplify)[799] <Error>: <private>`

```
amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_auth_cognito:
    dependency: "direct main"
    description:
      name: amplify_auth_cognito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_core:
    dependency: transitive
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
```
It's really kind of weird behavior. Only is happening in iOS. When I do change simulator it is working. That too sometime.
