### ISSUE TITLE
Error: The non-ASCII character 'ş' (U+015F) can't be used in identifiers, only in strings and comments.

### ISSUE THREAD

**Issue by abdullah017** [aws-amplify/amplify-flutter#1698]
### Description

***I CREATED A NEW PROJECT TO USE GRAPHQL API BUT I GET THIS ERROR WHEN RUNNING;

Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
: Error: The non-ASCII character 'ş' (U+015F) can't be used in identifiers, only in strings and comments.
Try using an US-ASCII letter, a digit, '_' (an underscore), or '$' (a dollar sign).
        şifthrow AmplifyException.fromMap(Map<String, String>.from(e.details));
        ^
: Error: 'şifthrow' isn't a type.
        şifthrow AmplifyException.fromMap(Map<String, String>.from(e.details));
        ^^^^^^^^
: Error: Expected ';' after this.
        şifthrow AmplifyException.fromMap(Map<String, String>.from(e.details));
                 ^^^^^^^^^^^^^^^^
: Error: Expected an identifier, but got '.'.
Try inserting an identifier before '.'.
        şifthrow AmplifyException.fromMap(Map<String, String>.from(e.details));
                                 ^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/abc/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
Process 'command '/Users/abc/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

* Get more help at https://help.gradle.org/
BUİLD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
I don't know if we report bugs here or on github, so I'm sharing it here. I'm sorry for that

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

I running the project

### Platforms

- [X] iOS
- [X] Android

### Environment

```bash
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale
    tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
nitiated
CREATE_IN_PROGRESS CommentpostResolver  AWS::AppSync::Resolver Wed Jun 08 2022 19:52:42 GMT+0300 (GMT+03:00) Resource creation Initiated
CREATE_COMPLETE    PostblogResolver     AWS::AppSync::Resolver Wed Jun 08 2022 19:52:42 GMT+0300 (GMT+03:00)                            
CREATE_IN_PROGRESS BlogpostsResolver    AWS::AppSync::Resolver Wed Jun 08 2022 19:52:42 GMT+0300 (GMT+03:00) Resource creation Initiated
CREATE_COMPLETE    CommentpostResolver  AWS::AppSync::Resolver Wed Jun 08 2022 19:52:42 GMT+0300 (GMT+03:00)                            
⠹ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE    BlogpostsResolver    AWS::AppSync::Resolver Wed Jun 08 2022 19:52:42 GMT+0300 (GMT+03:00)                            
CREATE_IN_PROGRESS PostcommentsResolver AWS::AppSync::Resolver Wed Jun 08 2022 19:52:43 GMT+0300 (GMT+03:00) Resource creation Initiated
CREATE_COMPLETE    PostcommentsResolver AWS::AppSync::Resolver Wed Jun 08 2022 19:52:43 GMT+0300 (GMT+03:00)                            
⠙ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE amplify-graphqldemo-dev-194209-apigraphqldemo-QIHESHJYZOK4-ConnectionStack-1G8S3ON3TTGP AWS::CloudFormation::Stack Wed Jun 08 2022 19:52:44 GMT+0300 (GMT+03:00) 
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE ConnectionStack AWS::CloudFormation::Stack Wed Jun 08 2022 19:52:50 GMT+0300 (GMT+03:00) 
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS CustomResourcesjson AWS::CloudFormation::Stack Wed Jun 08 2022 19:52:53 GMT+0300 (GMT+03:00)                            
CREATE_IN_PROGRESS CustomResourcesjson AWS::CloudFormation::Stack Wed Jun 08 2022 19:52:54 GMT+0300 (GMT+03:00) Resource creation Initiated
⠋ Updating resources in the cloud. This may take a few minutes...

CREATE_IN_PROGRESS amplify-graphqldemo-dev-194209-apigraphqldemo-QIHESHJYZOK4-CustomResourcesjson-R878QAA428BK AWS::CloudFormation::Stack Wed Jun 08 2022 19:52:53 GMT+0300 (GMT+03:00) User Initiated
⠏ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE amplify-graphqldemo-dev-194209-apigraphqldemo-QIHESHJYZOK4-CustomResourcesjson-R878QAA428BK AWS::CloudFormation::Stack Wed Jun 08 2022 19:52:59 GMT+0300 (GMT+03:00) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE CustomResourcesjson AWS::CloudFormation::Stack Wed Jun 08 2022 19:53:04 GMT+0300 (GMT+03:00) 
⠴ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE amplify-graphqldemo-dev-194209-apigraphqldemo-QIHESHJYZOK4 AWS::CloudFormation::Stack Wed Jun 08 2022 19:53:07 GMT+0300 (GMT+03:00) 
⠸ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE apigraphqldemo AWS::CloudFormation::Stack Wed Jun 08 2022 19:53:25 GMT+0300 (GMT+03:00) 
⠼ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-graphqldemo-dev-194209 AWS::CloudFormation::Stack Wed Jun 08 2022 19:53:28 GMT+0300 (GMT+03:00) 
UPDATE_COMPLETE                     amplify-graphqldemo-dev-194209 AWS::CloudFormation::Stack Wed Jun 08 2022 19:53:29 GMT+0300 (GMT+03:00) 
✔ All resources are updated in the cloud



GraphQL transformer version: 2

abdullahtas@abdullah-MacBook-Air graphql_demo % sudo amplify codegen models
Password:

abdullahtas@abdullah-MacBook-Air graphql_demo % flutter pub deps --no-dev --style=compact
Dart SDK 2.17.1
Flutter SDK 3.0.1
graphql_demo 1.0.0+1

dependencies:
- amplify_api 0.5.1 [amplify_api_plugin_interface amplify_core amplify_api_android amplify_api_ios collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.5.1 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_auth_plugin_interface amplify_core collection flutter plugin_platform_interface]
- amplify_datastore 0.5.1 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.5.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_analytics_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_api_android 0.5.1 [flutter]
- amplify_api_ios 0.5.1 [amplify_core flutter]
- amplify_api_plugin_interface 0.5.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.5.1 [flutter]
- amplify_auth_cognito_ios 0.5.1 [amplify_core flutter]
- amplify_auth_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_core 0.5.1 [collection date_time_format flutter meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.5.1 [flutter meta collection amplify_core]
abdullahtas@abdullah-MacBook-Air graphql_demo % flutter pub deps --no-dev --style=compact
Dart SDK 2.17.1
Flutter SDK 3.0.1
graphql_demo 1.0.0+1

dependencies:
- amplify_api 0.5.1 [amplify_api_plugin_interface amplify_core amplify_api_android amplify_api_ios collection flutter meta plugin_platform_interface]
- amplify_auth_cognito 0.5.1 [amplify_auth_cognito_android amplify_auth_cognito_ios amplify_auth_plugin_interface amplify_core collection flutter plugin_platform_interface]
- amplify_datastore 0.5.1 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.5.1 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_analytics_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_api_android 0.5.1 [flutter]
- amplify_api_ios 0.5.1 [amplify_core flutter]
- amplify_api_plugin_interface 0.5.1 [amplify_core collection flutter json_annotation meta]
- amplify_auth_cognito_android 0.5.1 [flutter]
- amplify_auth_cognito_ios 0.5.1 [amplify_core flutter]
- amplify_auth_plugin_interface 0.5.1 [amplify_core flutter meta]
- amplify_core 0.5.1 [collection date_time_format flutter meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.5.1 [flutter meta collection amplify_core]
- amplify_flutter_android 0.5.1 [flutter]
- amplify_flutter_ios 0.5.1 [amplify_core flutter]
- amplify_storage_plugin_interface 0.5.1 [flutter meta amplify_core]
- async 2.8.2 [collection meta]
- characters 1.2.0
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- date_time_format 2.0.1
- json_annotation 4.5.0 [meta]
- material_color_utilities 0.1.4
- meta 1.7.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
```

### Device

Iphone se 3nd generation,pixel 3 -Emulator

### OS

IOS 15 ANDROID 9.0

### CLI Version

8.4.0

**Comment by abdullah017** [comment]
showing error in method channel file**


/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

part of 'amplify_impl.dart';

const MethodChannel _channel = MethodChannel('com.amazonaws.amplify/amplify');

/// An implementation of [Core] that uses method channels.
class MethodChannelAmplify extends AmplifyClass {
  MethodChannelAmplify() : super.protected();

  AmplifyConfig? _config;

  bool _isConfigured = false;

  final _configCompleter = Completer<AmplifyConfig>();

  @override
  bool get isConfigured {
    return _isConfigured;
  }

  @override
  Future<AmplifyConfig> get asyncConfig {
    return _configCompleter.future;
  }

  @override
  Future<void> addPlugin(AmplifyPluginInterface plugin) async {
    if (_isConfigured) {
      throw const AmplifyAlreadyConfiguredException(
        'Amplify has already been configured and adding plugins after configure is not supported.',
        recoverySuggestion:
            'Check if Amplify is already configured using Amplify.isConfigured.',
      );
    }
    try {
      if (plugin is AuthPluginInterface) {
        await Auth.addPlugin(plugin);
        Hub.addChannel(HubChannel.Auth, plugin.streamController);
      } else if (plugin is AnalyticsPluginInterface) {
        await Analytics.addPlugin(plugin);
      } else if (plugin is StoragePluginInterface) {
        await Storage.addPlugin(plugin);
      } else if (plugin is DataStorePluginInterface) {
        try {
          await DataStore.addPlugin(plugin);
        } on AmplifyAlreadyConfiguredException {
          // A new plugin is added in native libraries during `addPlugin`
          // call for DataStore, which means during an app restart, this
          // method will throw an exception in android. We will ignore this
          // like other plugins and move on. Other exceptions fall through.
        }
        Hub.addChannel(HubChannel.DataStore, plugin.streamController);
      } else if (plugin is APIPluginInterface) {
        await API.addPlugin(plugin);
      } else {
        throw AmplifyException(
          'The type of plugin ${plugin.runtimeType} is not yet supported '
          'in Amplify.',
          recoverySuggestion:
              AmplifyExceptionMessages.missingRecoverySuggestion,
        );
      }
    } on Exception catch (e) {
      safePrint('Amplify plugin was not added');
      throw AmplifyException(
        'Amplify plugin ${plugin.runtimeType} was not added successfully.',
        recoverySuggestion: AmplifyExceptionMessages.missingRecoverySuggestion,
        underlyingException: e.toString(),
      );
    }
  }

  @override
  Future<void> addPlugins(List<AmplifyPluginInterface> plugins) {
    return Future.wait(plugins.map(addPlugin));
  }

  @override
  Future<void> configure(String configuration) async {
    // Validation #1
    if (_isConfigured) {
      throw const AmplifyAlreadyConfiguredException(
        'Amplify has already been configured and re-configuration is '
        'not supported.',
        recoverySuggestion: 'Check if Amplify is already configured using '
            'Amplify.isConfigured.',
      );
    }

    // Validation #2. Try decoding the json string
    try {
      jsonDecode(configuration);
    } on FormatException catch (e) {
      throw AmplifyException(
          'The provided configuration is not a valid json. Check underlyingException.',
          recoverySuggestion:
              'Inspect your amplifyconfiguration.dart and ensure that the string is proper json',
          underlyingException: e.toString());
    }
    try {
      await _configurePlatforms(_getVersion(), configuration);
      _isConfigured = true;
    } on PlatformException catch (e) {
      if (e.code == 'AnalyticsException') {
        throw AnalyticsException.fromMap(Map<String, String>.from(e.details));
      } else if (e.code == 'AmplifyException') {
        şifthrow AmplifyException.fromMap(Map<String, String>.from(e.details));
      } else if (e.code == 'AmplifyAlreadyConfiguredException') {
        _isConfigured = true;
      } else {
        // This shouldn't happen. All exceptions coming from platform for
        // amplify_flutter should have a known code. Throw an unknown error.
        throw AmplifyException(AmplifyExceptionMessages.missingExceptionMessage,
            recoverySuggestion:
                AmplifyExceptionMessages.missingRecoverySuggestion,
            underlyingException: e.toString());
      }
    }
    await DataStore.configure(configuration);

    if (_isConfigured && !_configCompleter.isCompleted) {
      _config = _parseConfigJson(configuration);
      _configCompleter.complete(_config);
    }
  }

  Future<void> _configurePlatforms(String version, String configuration) async {
    await _channel.invokeMethod<void>(
      'configure',
      <String, Object>{
        'version': version,
        'configuration': configuration,
      },
    );
    await Future.wait(
      //ignore:invalid_use_of_protected_member
      AnalyticsCategory.plugins.map((plugin) => plugin.onConfigure()),
    );
  }

  /// Parses the [configuration] string into an [AmplifyConfig] object.
  /// An empty [AmplifyConfig] is returned on exception.
  AmplifyConfig _parseConfigJson(String configuration) {
    try {
      return AmplifyConfig.fromJson(jsonDecode(configuration));
    } on Exception catch (e) {
      safePrint(
        'There was an unexpected problem parsing the amplifyconfiguration.dart file: $e',
      );
      return const AmplifyConfig();
    }
  }

  String _getVersion() {
    return '0.5.1';
  }
}

**Comment by HuiSF** [comment]
Interesting issue... I checked the source code on the v0.5.1 tag, I don't see that line

https://github.com/aws-amplify/amplify-flutter/blob/2c69e5df924d8387fa034ad4f5723af197074409/packages/amplify/amplify_flutter/lib/src/method_channel_amplify.dart#L117-L124

Did you accidentally modified installed package files? Can you try to clean the project, and rerun `flutter pub get` and return the App?

**Comment by abdullah017** [comment]
> Interesting issue... I checked the source code on the v0.5.1 tag, I don't see that line
> 
> https://github.com/aws-amplify/amplify-flutter/blob/2c69e5df924d8387fa034ad4f5723af197074409/packages/amplify/amplify_flutter/lib/src/method_channel_amplify.dart#L117-L124
> 
> Did you accidentally modified installed package files? Can you try to clean the project, and rerun `flutter pub get` and return the App?

Yes it's an interesting problem, I tried the following and didn't succeed;
flutter clean and flutter pub get

**Comment by Jordan-Nelson** [comment]
@abdullah017 can you include the contents of your pubspec.yaml and pubspec.lock file?

**Comment by abdullah017** [comment]
> @abdullah017 can you include the contents of your pubspec.yaml and pubspec.lock file?

PUBSPEC.YAML
```
name: graphql_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  amplify_flutter: ^0.5.0
  amplify_datastore: ^0.5.0
  amplify_api: ^0.5.0
  amplify_auth_cognito: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
---------------------------------------
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  amplify_analytics_plugin_interface:
    dependency: transitive
    description:
      name: amplify_analytics_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_api:
    dependency: "direct main"
    description:
      name: amplify_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_api_android:
    dependency: transitive
    description:
      name: amplify_api_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_api_ios:
    dependency: transitive
    description:
      name: amplify_api_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_api_plugin_interface:
    dependency: transitive
    description:
      name: amplify_api_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_auth_cognito:
    dependency: "direct main"
    description:
      name: amplify_auth_cognito
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_auth_cognito_android:
    dependency: transitive
    description:
      name: amplify_auth_cognito_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_auth_cognito_ios:
    dependency: transitive
    description:
      name: amplify_auth_cognito_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_auth_plugin_interface:
    dependency: transitive
    description:
      name: amplify_auth_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_core:
    dependency: transitive
    description:
      name: amplify_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_datastore:
    dependency: "direct main"
    description:
      name: amplify_datastore
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_datastore_plugin_interface:
    dependency: transitive
    description:
      name: amplify_datastore_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_flutter:
    dependency: "direct main"
    description:
      name: amplify_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_flutter_android:
    dependency: transitive
    description:
      name: amplify_flutter_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_flutter_ios:
    dependency: transitive
    description:
      name: amplify_flutter_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  amplify_storage_plugin_interface:
    dependency: transitive
    description:
      name: amplify_storage_plugin_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.1"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.2"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.16.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.2"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  date_time_format:
    dependency: transitive
    description:
      name: date_time_format
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.0"
  lints:
    dependency: transitive
    description:
      name: lints
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.11"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.0"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.1"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.2"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.9"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.6"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2"
sdks:
  dart: ">=2.17.1 <3.0.0"
  flutter: ">=2.0.0"

```
