### ISSUE TITLE
where is 'safePrint' ?

### ISSUE THREAD

**Issue by lien-dkseo** [aws-amplify/amplify-flutter#2092]
https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/#initialize-amplify-api
```
} on AmplifyAlreadyConfiguredException {
  safePrint('Tried to reconfigure Amplify; this can occur when your app restarts on Android.');
}
```

`The method 'safePrint' isn't defined for the type ...`

**Comment by dnys1** [comment]
Hi @lien-dkseo - which versions of the Amplify libraries are you using? Can you double check you are using either the latest stable versions (`^0.6.0`) or the latest dev-preview versions (`^1.0.0-0`)?

**Comment by lien-dkseo** [comment]
Hi~ @dnys1 

```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  amplify_flutter: ^0.6.6
  amplify_datastore: ^0.6.6
  amplify_datastore_plugin_interface: ^0.6.6
  amplify_api: ^0.6.6
  amplify_auth_cognito: ^0.6.6
  amplify_core: ^0.6.6
```

```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.918], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.71.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
```
