### ISSUE TITLE
After verification code mismatch can't resubmit correct code.

### ISSUE THREAD

**Issue by asaarnak** [aws-amplify/amplify-flutter#2467]
### Description

Authenticate with invalid verification code and after that authenticating with correct verification code fails.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

```dart
  Future<String> verifyLoginCode(String invalidVerificationCode) async {
    try {
      await Amplify.Auth.confirmSignIn(confirmationValue: invalidVerificationCode);
    } on CodeMismatchException {
      try {
        await Amplify.Auth.confirmSignIn(confirmationValue: correctVerificationCode);
      } on AmplifyException catch (exception) {
        if (exception.message == 'There is no active challenge') {
          // TODO fix this, impossible to login by entering correctVerificationCode if 
        }
      }
    }
  }
```

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
[✓] Flutter (Channel stable, 3.3.9, on Ubuntu 22.10 5.19.0-26-generic, locale en_US.UTF-8)
    • Dart version 2.18.5
```

### Dependencies

```bash
pubspec.yaml
  amplify_flutter: ^1.0.0-next.1+1
  amplify_auth_cognito: ^1.0.0-next.1+1

pubspec.lock
  amplify_auth_cognito_dart:
    dependency: transitive
    description:
      name: amplify_auth_cognito_dart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.5"
```

### Device

SM N986B

### OS

Android 13

### Deployment Method

Amplify CLI

### Amplify Config

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "",
                            "Region": ""
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "",
                        "AppClientId": "",
                        "Region": ""
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

**Comment by asaarnak** [comment]
Thanks for working on this so fast!
Is it possible to make a hot fix on dependency override for `amplify_auth_cognito_dart`?
@dnys1

**Comment by asaarnak** [comment]
Dependency override gives me this error.
Any way around it? @dnys1 @cshfang 
```bash
Running Gradle task 'assembleDevelopmentDebug'...
Error detected in pubspec.yaml:
No file or variants found for asset: packages/amplify_auth_cognito_dart/lib/src/workers/workers.min.js.

This asset was included from package amplify_auth_cognito_dart.
```
```yaml
dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.0.0-next.1+1
  amplify_auth_cognito: ^1.0.0-next.1+1
  
dependency_overrides:
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/amplify/amplify_flutter
  amplify_flutter_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/amplify/amplify_flutter_android
  amplify_flutter_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/amplify/amplify_flutter_ios
  amplify_secure_storage:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/secure_storage/amplify_secure_storage_dart
  amplify_core:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/amplify_core
  amplify_datastore_plugin_interface:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/amplify_datastore_plugin_interface
  amplify_auth_cognito_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/auth/amplify_auth_cognito_android
  amplify_auth_cognito_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/auth/amplify_auth_cognito_ios
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/auth/amplify_auth_cognito
  amplify_auth_cognito_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: afaec3cb133a082f9eb8aa0df66234543b5d2759
      path: packages/auth/amplify_auth_cognito_dart
```
