### ISSUE TITLE
DataStore plugin not found on existing Amplify project

### ISSUE THREAD

**Issue by pkhivesara** [aws-amplify/amplify-flutter#265]
**Describe the bug**
Amplify DataStore plugin not found.

**To Reproduce**
1. Add ``amplify_datastore: '<1.0.0'`` to ``pubspec.yaml`` file
2. Run ``flutter packages get``
3. Execute ``amplify pull`` to download existing Amplify backend
4. Execute ``amplify update api``
5. Run ``amplify codegen models`` to generate the models.
6. Add the following to initialization in ``main.dart``

```
import 'codegen/ModelProvider.dart';

// Add this in your app initialization
AmplifyDataStore datastorePlugin =
    AmplifyDataStore(modelProvider: ModelProvider.instance);
amplifyInstance.addPlugin(dataStorePlugins: [datastorePlugin]);
```

7. Try to run the app. IDE throws a compilation error:
```
Target of URI doesn't exist: 'package:amplify_datastore/amplify_datastore.dart'.  Try creating the file referenced by the URI, or Try using a URI for a file that does exist

Target of URI doesn't exist: 'package:amplify_datastore_plugin_interface/amplify_datastore_plugin_interface.dart'.  Try creating the file referenced by the URI, or Try using a URI for a file that does exist.
```

**Expected behavior**
``amplify_datastore`` package should be available in IDE.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[x] iOS

**Additional context**
Android Studio: 4.1.1
Amplify CLI: 4.40.0
OS: macOS Catalina

**Comment by jamesonwilliams** [comment]
Hi @pkhivesara! Did you go through all of the [project setup steps in the guide](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter#project-setup)?

What's the full contents of your `pubpec.yaml`?

What output do you see when you run `flutter pub get  --verbose`? Any errors/warning/hints?

**Comment by pkhivesara** [comment]
Hi @jamesonwilliams 
The pubspec file:

```
name: xxx
description: xxx

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_datastore: '<1.0.0'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

And I dont see any warnings as such. Though I do see a bunch of ``SVLR`` after running ``flutter pub get --verbose``

``` fact: amplify_core_plugin_interface 0.0.1-dev.4 depends on amplify_storage_plugin_interface ^0.0.1-dev.4
[        ] SLVR:                                                                   fact: amplify_core_plugin_interface 0.0.1-dev.4 depends on amplify_auth_plugin_interface ^0.0.1-dev.4
[        ] SLVR:                                                                   fact: amplify_core_plugin_interface 0.0.1-dev.4 depends on amplify_analytics_plugin_interface ^0.0.1-dev.4
[        ] SLVR:                                                                   fact: amplify_core_plugin_interface 0.0.1-dev.4 depends on amplify_datastore_plugin_interface ^0.0.1-dev.4

```
