### ISSUE TITLE
Question with automated deployment Git Actions - amplifyconfigurations.dart

### ISSUE THREAD

**Issue by c-reschke** [aws-amplify/amplify-flutter#2682]
Hello. I have a question about automated deploy with Git Actions. How do I securely pass the amplifyconfigurations.dart file so I can build the application release? The code below is working but I don't know how to do it with amplifyconfigurations.

```
on:
  push:
    branches:
      - ci-cd

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Amplify configurations from base64
        env:
          AMPLIFY_CONF: ${{ secrets.DYNAMICS_AMPLIFY_CONFIGURATIONS }}
        run: |
          echo $AMPLIFY_CONF | base64 -d
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"

      # Setup the flutter environment.
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           channel: 'stable'

      - run: flutter pub get
#      - run: dart format --set-exit-if-changed .
      - run: dart format .
      - run: flutter analyze .
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter build appbundle --release -t lib/main.dart --dart-define=APP_NAME=${{ vars.DYNAMICS_APP_NAME }} --dart-define=MAP_KEY=${{ secrets.DYMANICS_MAP_KEY }}

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK

        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.DYNAMICS_KEYSTORE_KEY }}
          alias: ${{ secrets.DYNAMICS_KEY_ALIAS}}
          keyStorePassword: ${{ secrets.DYNAMICS_KEYSTORE_PASS }}
          keyPassword: ${{ secrets.DYNAMICS_KEY_PASS }}
#
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: app-release.aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
```
Thanks
