### ISSUE TITLE
Sign calls to other AWS Services with Amplify API Plugin

### ISSUE THREAD

**Issue by blattr** [aws-amplify/amplify-flutter#2758]
Hello everyone,

I am stuck with a problem and I was hoping to find some help from you guys. Basically my App is using Cognito (UserPools+Identity), several API Gateways and an OpenSearch endpoint (see the snippet of my Amplify configuration below).

Calls to my API Gateway(s) succeed but when I try to call the OpenSearch endpoint, the call fails with a **HTTP 403**:

`Credential should be scoped to correct service: 'es'.`

I only can guess, that the Amplify API Plugin is using **execute-api** as service name by default (which makes sense, as long as you are calling API Gateways). But I don't understand, why the plugin is not simply able to determine the service by the endpoint I am calling - so in my case - putting **es** as service name whenever I call OpenSearch. 
Furthermore, I am also using a custom domain for my OpenSearch (https://search.someapi.com) to make things more understandable. It would be awesome if I could force the Amplify API Plugin to use a specific service name.

Is there any trick, any hack or a feature on the roadmap to make this simply work with the official Amplify Plugin? At the moment I am using a third party plugin (amazon_cognito_identity_dart_2) to sign my calls to the OpenSearch endpoint on my own. I mean, come on...

Just to be clear, my resources are all setup correctly. The App is working! But it would be a huge improvement if the Amplify API Plugin was able to call any AWS Services (with AWS_IAM as authorization type of course). The solution to this - in my understanding - is to simply change the service name, which is used to sign the request. This is a super low hanging fruit :-)

```json
"api": {
      "plugins": {
          "awsAPIPlugin": {
              "api-gateway-1": {
                  "endpointType": "REST",
                  "endpoint": "https://xxx.execute-api.eu-central-1.amazonaws.com",
                  "region": "eu-central-1",
                  "authorizationType": "AWS_IAM"
              },
              "opensearch": {
                  "endpointType": "REST",
                  "endpoint": "https://xxx.eu-central-1.es.amazonaws.com",
                  "region": "eu-central-1",
                  "authorizationType": "AWS_IAM"
              }
          }
      }
  }
```

**Comment by dnys1** [comment]
Hi @blattr, sorry you are facing this issue. The REST API category is specifically for interacting with API Gateway and is not designed for interacting with other AWS services.

To interact with those services, the best approach currently would be to use a high-level API like [`aws_es_api`](https://pub.dev/packages/aws_es_api) with credentials from the [Auth category](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter/). This is an unofficial package, but the only alternative would be to use the [`aws_signature_v4`](https://pub.dev/packages/aws_signature_v4) package directly to sign service calls, again using the credentials provided by the Auth category.

Hope this helps.

**Comment by blattr** [comment]
> Hi @blattr, sorry you are facing this issue. The REST API category is specifically for interacting with API Gateway and is not designed for interacting with other AWS services.
> 
> To interact with those services, the best approach currently would be to use a high-level API like [`aws_es_api`](https://pub.dev/packages/aws_es_api) with credentials from the [Auth category](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter/). This is an unofficial package, but the only alternative would be to use the [`aws_signature_v4`](https://pub.dev/packages/aws_signature_v4) package directly to sign service calls, again using the credentials provided by the Auth category.
> 
> Hope this helps.

First of all, big thanks for the quick reply. Unfortunately both of your suggested answers do **not** work because:

- from what I have seen, **aws_es_api** is made/generated to use the API of the AWS OpenSearch Service itself, but I have to perform calls to the index(es) of my OSS (**/index/_search**, **/index/_bulk** etc.)
- AWS Amplify (even in the latest version - which is **0.6.12**) is bound to aws_common **0.1.1**, what makes it incompatible with any version of the **aws_signature_v4** package. This is already a tracked issue if I am not wrong

Maybe I should rethink my question... how is Amplify signing its requests? Any internal package I can use out of the box? :-)

**Comment by blattr** [comment]
Hello again,

I just want to share my experience with the **aws_signature_v4** package with you guys and (unfortunately) I have another question for you @dnys1 

### Supported HTTP protocol
This is a strange one. I used to send my requests with the default instance of an **AWSHttpClient** - which is using any HTTP protocol available (**SupportedProtocols.http1_2_3**).
Out of nowhere, a very strange error came up. Whatever request I sent, it did not get through and ended up with the following message:

`HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 1).`

I tried very hard to investigate but I came to a dead end where I gave up. However, this seems to be a known bug - or at least there are other plugins which struggle with this behavior ([https://github.com/cfug/dio/issues/486](https://github.com/cfug/dio/issues/486)). After I set the supported HTTP operation to 1 only (**SupportedProtocols.http1**) everything works fine.

### Special characters in query parameters
Unfortunately, there are very few examples on how to use the SigV4Signer with query parameters and the ones I saw only used them without special signs. I am crafting my query parameter map like this ($text is any text a user enters into a search text field):

```dart
...

queryParams: {
    "q": "$text*",
    "pretty": "true",
    "size": "5",
}
...

AWSHttpRequest request = AWSHttpRequest.raw(
    method: AWSHttpMethod.get,
    host: endpoint,
    path: path,
    queryParameters: queryParams,
    headers: {
      AWSHeaders.host: endpoint,
    },
);
```

AWS returns a 403 with the following message:

```
The Canonical String for this request should have been
GET
/places/_search
pretty=true&q=Berg%2A&size=5
host:search.dev.xxx.com
x-amz-content-sha256:e3b0c44298fc1c14...
x-amz-date:20230320T081651Z
x-amz-security-token:IQoJb3JpZ...
```

When I remove the asteriks from my query parameter, the request goes through - everything works just fine (except for my search result of course :-) ). I investigated the calculation of the signature but was not able to get to the part where it goes wrong. When I print out the canonical string of the signed request before sending it to AWS (with the asteriks), it is the following output:

```dart
print(signedRequest.canonicalRequest);
```

```
GET
/places/_search
pretty=true&q=Berg*&size=5
host:search.dev.xxx.com
x-amz-content-sha256:e3b0c44298fc1c14...
x-amz-date:20230320T081651Z
x-amz-security-token:IQoJb3JpZ...
```

I do not know if this is just an "optical" issue but as you can see, the asteriks in the canonical request is not encoded properly.

@dnys1 can you tell me what I am doing wrong? Do you need more information to investigate this behavior on your side? I guess I am not the only one who encountered this.

Best regards and again, thank you so much for helping me!

**Comment by dnys1** [comment]
Thanks for the incredible deep dive, @blattr! I appreciate the resources and it appears you uncovered a couple issues in our signing implementation.

I've created a [PR](https://github.com/aws-amplify/amplify-flutter/pull/2765) to fix these issues and will keep you posted when it is merged. In the meantime, you can add overrides for `aws_common` and `aws_signature_v4` to get the fixes:

```dart
dependency_overrides:
  aws_common:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: feat/http/more-e2e-tests
      path: packages/aws_common
  aws_signature_v4:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: feat/http/more-e2e-tests
      path: packages/aws_signature_v4
```

**Comment by blattr** [comment]
@dnys1 you are welcome. Sharing is caring... 

Just a quick response - both issues disappeared with the overridden dependencies :-)

**Comment by Jordan-Nelson** [comment]
@blattr - Let us know if you are still facing an issue, or still have questions about this.

**Comment by dnys1** [comment]
Thanks for the update, @blattr. Yes, that's the correct service name - it is very confusing indeed!

Please keep us posted. Your feedback is invaluable in preparing docs and resources for future users 🙏

**Comment by blattr** [comment]
**Disclaimer**: This is a bit off-topic. My initial question is absolutely **answered** but I would love to understand the second issue mentioned above, too.

I try to explain where my confusion is coming from.

### Access with IAM User
When I am calling a search endpoint of my OpenSearch Service like "/my-index/_search", everything works. I use to make these calls with Postman and the AWS Signature as authentication method. Obviously I am using my personal user, which has access to anything - so this is not really a big surprise.

When I add an access policy to OpenSearch Service like:

```yaml
AccessPolicies:
  Version: "2012-10-17"
  Statement:
    - Effect: "Deny"
      Principal:
        AWS: "*"
      Action: "*"
      Condition:
        StringEquals: 
          "aws:ResourceAccount": 
            Fn::Sub: "${AWS::AccountId}"
``` 

.. even my administrative user cannot perform index related actions anymore, which also makes sense for me (with OpenSearch you can only limit index access within the resource based policy, not service functions).

Because you are forced to add an access policy, I added the following, which basically excludes all AWS principals outside my account (seems fair enough, doesn't it?):

```yaml
AccessPolicies:
  Version: "2012-10-17"
  Statement:
    - Effect: "Deny"
      Principal:
        AWS: "*"
      Action: "*"
      Condition:
        StringNotEquals: 
          "aws:ResourceAccount": 
            Fn::Sub: "${AWS::AccountId}"
``` 

With this setup, my user is able to to anything, with any index. Perfect!

### Access with IAM Role
As I explained before, I like the idea of having to empty roles within my auth stack (authenticated+unauthenticated) and add policies in the specific services. With this technique, every service can decide on its own, who can access its endpoint.

In my Search Service Stack I added following policy to the unauthenticated role:

```yaml
PolicyDocument:
  Version: "2012-10-17"
  Statement:
    - Effect: "Allow"
      Action: "es:ESHttpGet"
      Resource: 
        Fn::Sub: "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/my-domain-${EnvironmentStage}/my-index/_search"
```

I double checked the IAM role to make sure, this policy found its way in it. I assumed, my unauthenticated role (which I successfully used to call the AGW) is now able to search in/on my index. But I get this message:

`User: arn:aws:sts::123456789:assumed-role/auth-service-unauthenticated-role-dev/CognitoIdentityCredentials is not authorized to perform: es:ESHttpGet because no session policy allows the es:ESHttpGet action`

When I explicitly allow this action in my resource based policy in OpenSearch like this:

```yaml
AccessPolicies:
  Version: "2012-10-17"
  Statement:
    - Effect: "Allow"
      Principal:
        AWS:
          Fn::Sub:
            - "arn:aws:sts::${AWS::AccountId}:assumed-role/${UnauthenticatedRoleName}/CognitoIdentityCredentials"
            - UnauthenticatedRoleName:
                Fn::ImportValue:
                  Fn::Sub: "auth-service-stack-${EnvironmentStage}-unauthenticated-role-name"
      Action: "es:ESHttpGet"
      Resource:
        - Fn::Sub: "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/my-domain-${EnvironmentStage}/my-index/_search"
```

... guess what. It is working. I don't understand, why my role policies are "ignored". There is no explicit deny in the resource based policy of OpenSearch so I would assume, the "Allow" wins the privilege.

This is very annoying because it is against my understanding of how IAM works (and I have to say, I am not a rookie in this topic).
