### ISSUE TITLE
After I've authenticated with Google, but Amplify Flutter recognized me as guest user.

### ISSUE THREAD

**Issue by naoyashiga** [aws-amplify/amplify-flutter#290]
**Describe the bug**
I've authenticated with Google, but Amplify Flutter treats it as guest authentication.

Log said this.

```
D/AWSMobileClient(13297): waitForSignIn: userState:GUEST
```

**Current status**

・Google authentication was possible via Host UI 
(Google authentication was also possible by directly sending a request to the authorization endpoint).

・As a result of the federation, I was able to get the authorization code.

・I was able to obtain user pool tokens (idtoken, referesh token, access_token) using the authorization code.

・The email address of the authenticated user can be obtained using the USERINFO endpoint.

・I can see the authenticated user's information from Cognito's user pool management console.

**Expected behavior**
After sending a request to the token endpoint and receiving a response, signup (login) is complete. I can use Datastore and Storage with authentication.

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[Y] Android
[] iOS（I have not tested on iPhone yet）

**Library**
```yaml
dependencies:
  flutter:
    sdk: flutter
  amplify_core: '^0.0.1-dev.5'
  amplify_auth_cognito: '^0.0.1-dev.5'
  amplify_analytics_pinpoint: '^0.0.1-dev.5'
  amplify_datastore: '^0.0.1-dev.5'
  amplify_storage_s3: '^0.0.1-dev.5'
  # use when opening Host UI or authorization endpoint.
  flutter_web_auth: ^0.2.4
  # post request to token endpoint
  http: ^0.12.2
```
