### ISSUE TITLE
Unable to build the latest version of amplify_datastore with latest version of amplify_flutter

### ISSUE THREAD

**Issue by soheb12** [aws-amplify/amplify-flutter#2986]
### Description

I am trying to build the latest version of amplify_datastore: 0.6.13 with latest version of amplify_flutter: ^1.0.1

Here's how my pubspec.yaml file looks like:
```
dependencies:
  amplify_auth_cognito: ^1.0.1
  amplify_datastore: ^0.6.0
  amplify_flutter: ^1.0.1
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  draggable_home: ^1.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  amplify_datastore_plugin_interface: ^1.0.0
  amplify_core: ^1.0.1
  aws_common: ^0.4.2+5
```

I am running into this error

```
Error: Type 'HubEventPayload' not found.
amplify_datastore_stream_controller.dart:114
_rebroadcast(String eventName, {HubEventPayload? payload}) {
                                ^^^^^^^^^^^^^^^
: Error: 'HubEventPayload' isn't a type.
amplify_datastore_stream_controller.dart:114
_rebroadcast(String eventName, {HubEventPayload? payload}) {
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Storage

### Steps to Reproduce

1. Go to pubspec.yaml file and update it with this:
```
dependencies:
  amplify_auth_cognito: ^1.0.1
  amplify_datastore: ^0.6.0
  amplify_flutter: ^1.0.1
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  draggable_home: ^1.0.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  amplify_datastore_plugin_interface: ^1.0.0
  amplify_core: ^1.0.1
  aws_common: ^0.4.2+5
```
2. Run `flutter pub get`
3. You will see the error on your screen

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.11

### Amplify Flutter Version

1.0.1

### Deployment Method

Amplify CLI
