### ISSUE TITLE
iOS isn't throwing an AuthError when the user is not confirmed

### ISSUE THREAD

**Issue by BrandowBuenos** [aws-amplify/amplify-flutter#3053]
### Description

When trying to authenticate using a user with "Account status" "UNCONFIRMED" on iOS the library doesn't throw an Error. While in Android the library throws an AuthError with the details of the Error showing that the user is not confirmed.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Execute Amplify.Auth.signUp to create a new user, but don't call Amplify.Auth.confirmSignUp.
2. Execute Amplify.Auth.signIn using the previously created user.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.0

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by BrandowBuenos** [comment]
@Jordan-Nelson 

```
...

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  amplify_api: ^1.1.0
  amplify_auth_cognito: ^1.1.0
  amplify_datastore: ^1.1.0-supports-only-mobile
  amplify_flutter: ^1.1.0

...
```
