### ISSUE TITLE
Publishing Amplify Flutter packages breaks apps that refer to older versions of the SDK

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#373]
When a new version of amplify-flutter is released apps that depend on older versions of the SDK end up pulling artifacts from the new SDK.

The pubspec.yaml being used to build the SDK refers to its own version using '^' instead of a specific version. Ex:
```yaml
dependencies:
  flutter:
    sdk: flutter
  amplify_auth_plugin_interface: ^0.0.2-dev.2
  amplify_core: ^0.0.2-dev.2
  plugin_platform_interface: ^1.0.1
```
Therefore any app that refers to say `0.0.2-dev.1` may instead get `0.0.2-dev.2` artifacts pulled in for some transitive dependencies.

**Comment by kjones** [comment]
Example build where you see amplify_auth_cognito-0.0.2-dev.1 fail due to building with transitive dependencies that got pulled in from 0.0.2-dev.2.
```
../../programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.0.2-dev.1/lib/method_channel_auth_cognito.dart:285:13: Error: The getter 'AmplifyDartExceptions' isn't defined for the class 'AmplifyAuthCognitoMethodChannel'.
 - 'AmplifyAuthCognitoMethodChannel' is from 'package:amplify_auth_cognito/method_channel_auth_cognito.dart' ('../../programs/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.0.2-dev.1/lib/method_channel_auth_cognito.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'AmplifyDartExceptions'.
      throw(AmplifyDartExceptions.formatException(methodName: method, field: "nextStep"));
            ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by fjnoyp** [comment]
Thanks for bringing this to our attention @kjones 

Could you share your pubspec.yaml here?  Do you import your dependencies like (1) or (2)? 

(1)
  amplify_flutter: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'

(2) 
  amplify_flutter: ^0.0.2-dev.1
  amplify_auth_cognito: ^0.0.2-dev.1
  amplify_analytics_pinpoint:^0.0.2-dev.1

**Comment by kjones** [comment]
We specify versions explicitly:
```yaml
name: some_app
publish_to: none
version: 1.2.0

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.0
  material_design_icons_flutter: 4.0.5855

  date_range_picker: 1.0.6
  smart_select: 4.3.2

  firebase_core: 0.7.0
  firebase_crashlytics: 0.4.0+1
  firebase_analytics: 7.0.1

  auto_route: 0.6.9
  cached_network_image: 2.5.0
  carousel_slider: 2.3.1
  equatable: 1.2.5
  flutter_bloc: 6.1.1
  freezed_annotation: 0.12.0
  get_it: 5.0.6
  injectable: 1.0.7
  intl: 0.16.1
  kt_dart: 0.8.0
  logger: 0.9.4
  rxdart: 0.25.0
  shared_preferences: 0.5.12+4
  sprintf: 5.0.0
  tuple: 1.0.3
  uni_links: 0.4.0
  url_launcher: 5.7.10
  uuid: 2.2.2
  webview_flutter: 1.0.7
  package_info: 0.4.3+2
  auto_size_text: 2.1.0
  scrollable_positioned_list: 0.1.9
  youtube_player_iframe: 1.1.0
  youtube_explode_dart: 1.7.5
  visibility_detector: 0.1.5
  flutter_speed_dial: 1.2.5

  amplify_flutter: 0.0.2-dev.2
  amplify_auth_cognito: 0.0.2-dev.2
  amplify_datastore: 0.0.2-dev.2

dev_dependencies:

  # Test dependencies.
  bdd_widget_test:
  golden_toolkit:
  gherkin:
  mockito:
  glob:
  test:
  flutter_test:
    sdk: flutter

  # Build and analyzer dependencies.
  lint:
  build_runner:
  auto_route_generator: 0.6.10
  freezed: 0.12.7
  json_serializable: 3.5.1
  injectable_generator: 1.0.7

flutter:
  uses-material-design: true

```
