### ISSUE TITLE
iOS Crash after sign in

### ISSUE THREAD

**Issue by adplant** [aws-amplify/amplify-flutter#4092]
### Description

[packages.txt](https://github.com/aws-amplify/amplify-flutter/files/13305035/packages.txt)
[ios_crash_report_after_sign_in.txt](https://github.com/aws-amplify/amplify-flutter/files/13305039/ios_crash_report_after_sign_in.txt)

I've attached the packages I used and the crash report from TESTFLIGHT.

Basically, when I download and open up the app via testflight, things work for the sign in page, but a few seconds after I sign in the app crashes.

IMPORTANT NOTES:
- This only happens on the iOS app (I build an Android app as well, both via codemagic CI/CD)
- This only happens when I get the built app via testflight. When I build in release mode on a real device through vscode, it works.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. open app from testflight
2. sign in
3. wait a few seconds and then the app crashes

iOS only! Android works fine.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.9

### Amplify Flutter Version

1.6.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @adplant - I think this may be the result of a bug in the Flutter SDK that was recently resolved in Flutter's beta channel. See: https://github.com/flutter/flutter/issues/134548. Would you be willing to upgrade to Flutter beta and see if this is still reproducible?

**Comment by adplant** [comment]
@Jordan-Nelson Yeah I'll try it out

**Comment by adplant** [comment]
@Jordan-Nelson Switching to the latest beta channel did NOT work.

Also, of note, my whole app seemed to be in dark mode (not sure if that's what's supposed to happen or not).

**Comment by Jordan-Nelson** [comment]
Hm okay.

You mentioned that the crash happens a few seconds after sign in. Is there code that your app would be running after sign in?

Does it crash every time after login?

Are you seeing this on all devices?

**Comment by adplant** [comment]
@Jordan-Nelson Yes. Code runs after the sign in. It's hard to know exactly what's running because, like I mentioned, when I build in release mode locally it works so I don't see where it fails.

I'll look at the code and try to find out what should be running. I'll let you know soon.

As for devices... Yes, it's in multiple iPhones. But strictly iPhones. Android build works great.

**Comment by Jordan-Nelson** [comment]
There is a reference to [this file from Amplify Swift](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/API/Sources/AWSAPIPlugin/SubscriptionFactory/AWSSubscriptionConnectionFactory.swift) in the crash report, which is interesting. The Datastore category within Amplify Flutter depends on Amplify Swift, but if you are not using Datastore, Amplify Swift should not be used.

I have a few follow up questions:
- Are you using the Datastore category at all? 
- Can you confirm that you are using Amplify Flutter version 1.6.0 (including in Codemagic)
- Are you using Amplify Swift directly at all?

**Comment by adplant** [comment]
@Jordan-Nelson 

I'm using Datastore, GraphQl API, and Auth as plugins `AmplifyAPI(), AmplifyDataStore(), AmplifyAuthCognito()`.

I'm using Amplify Flutter 1.6.0 (My pubspec.lock says so, but I can't actually see the version from the codemagic output. It does the same `flutter pub get` with the pubspec.yaml stating `amplify_flutter: ^1.0.0` and the output in codmagic just shows what I listed in the `packages.txt` file in the description of this ticket.)

I am NOT using Amplify Swift directly.

**Comment by adplant** [comment]
@Jordan-Nelson Here is the consol log of what it should look like directly after a successful login and up to where the user would be ready to use the app.

[Post_loggin_log.txt](https://github.com/aws-amplify/amplify-flutter/files/13314164/Post_loggin_log.txt)

**Comment by adplant** [comment]
@Jordan-Nelson I just updated the last comment to provide both ios and android logs of what SHOULD be happening. They were produced from local builds.

**Comment by Jordan-Nelson** [comment]
From the crash log it seems like datastore is attempting to start multiple times. What datastore operations do you invoke after sign in? Can you share the relevant code that is invoked after sign in?

**Comment by adplant** [comment]
@Jordan-Nelson I'll try to get that together for you sometime today. And I could see that being true.

But why would this all of a sudden start crashing the app? It's been this way for over a year.

**Comment by Jordan-Nelson** [comment]
@adplant - were previous builds working even through Code Magic? If so, did you recently make any changes or upgrade flutter and/or amplify?

**Comment by adplant** [comment]
Yes. All builds worked fine through codemagic and then, yes, I upgraded flutter and packages.

**Comment by Jordan-Nelson** [comment]
Do you know what version of Flutter and Amplify Flutter you were previously using?

**Comment by adplant** [comment]
@Jordan-Nelson Flutter Version was 3.7.11 (because we'd noticed a bug causing issues, so we'd stayed on this for a while)
Amplify Flutter Version: We've just had the pubspec.yaml file say `amplify_flutter: ^1.0.0` for about 3 months, so we just keep getting the newest version, so it wasn't an issue with that.

**Comment by Jordan-Nelson** [comment]
Okay. Can you see if this issue is reproducible with the older version of flutter?

**Comment by adplant** [comment]
@Jordan-Nelson you want me to maintain the same pubspec.yaml file when I do that?

Should I use that same flutter version I had it last work with, or just any previous version?

**Comment by adplant** [comment]
@Jordan-Nelson I can't go back to Flutter 3.7.11 without also implementing older versions for a bunch of the packages (amplify packages included). Mainly due to the Dart Version being < 3.0.0.

**Comment by Jordan-Nelson** [comment]
Okay. Yes, Amplify Flutter v1.0.x was the last version to support an earlier version of dart. So it seems like everything was working with Amplify Flutter 1.0.x and Flutter 3.7.11 and is no longer working with Amplify Flutter 1.6.0 and Flutter 3.13.9.

We can see if anything that changed in Amplify could be the cause. If you are able to try to reproduce this with Amplify Flutter 1.1.0 (which was the first version to support dart 3.0) that might narrow it down.

**Comment by adplant** [comment]
@Jordan-Nelson Yeah, I'll try it out right now and report back.

**Comment by adplant** [comment]
@Jordan-Nelson Are you suggesting that I used the Stable Flutter version (3.13.9) while doing this?

**Comment by adplant** [comment]
@Jordan-Nelson  Ok, here's what I did. I am using the current Flutter version (3.13.9) and I changed the `amplify_flutter` package to 1.0.0. I also had to downgrade my `connectivity_plus` package b/c of conflicts.

Here's my pubspec.yaml:
```
environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_datastore: ^1.0.0-supports-only-mobile.0
  amplify_flutter: 1.1.0 #^1.0.0
  animated_text_kit: ^4.2.2
  connectivity_plus: null #^5.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_timezone: null
  flutter_riverpod: ^2.1.3
  fluttertoast: ^8.0.9
  geolocator: ^10.1.0
  intl: null
  jwt_decode: ^0.3.1
  mobile_scanner: ^3.5.1
  nfc_manager: ^3.2.0
  package_info_plus: ^4.2.0
  protobuf: null
  shared_preferences: ^2.0.17
```

Here's my pubspec.lock:
[pubspec.lock_amplify_flutter1.0_connectivity_plus3.0.6.txt](https://github.com/aws-amplify/amplify-flutter/files/13339972/pubspec.lock_amplify_flutter1.0_connectivity_plus3.0.6.txt)

It failed again.

Here is the crash log:
[crash_log_flutter3.13.9_amplify_flutter1.0.0_connectivity_plus3.0.6.txt](https://github.com/aws-amplify/amplify-flutter/files/13340262/crash_log_flutter3.13.9_amplify_flutter1.0.0_connectivity_plus3.0.6.txt)
