### ISSUE TITLE
Datastore codegen created models don't respect Dart linting rules

### ISSUE THREAD

**Issue by cto-leaps** [aws-amplify/amplify-flutter#462]
**Describe the bug**
CLI codegen models creates QueryFields that use uppercased variables.

Example:
`static final QueryField **SESSIONID** = QueryField(fieldName: "sessionID");`

They get picked up by the IDE as 
`Name non-constant identifiers using lowerCamelCase.dart(non_constant_identifier_names)`

**To Reproduce**
1. Create a graphql schema
2. Run amplify codegen models
3. Scroll down to 'static final QueryField.'
4. See the IDE screaming for non_constant_identifier_names errors

**Expected behavior**
Respecting dart listing rules

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[X] Android
[X] iOS

Amplify CL version 4.45.2
<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-arm, locale en-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)```

</details>

**Comment by kjones** [comment]
Re-adding my wish list from #241.

**Wish list**
- Generated model code should at least pass all [pedantic](https://pub.dev/packages/pedantic) linter rules and not rely on implicit or dynamic casts. Other more strict options welcome (e.g. [lint rules](https://pub.dev/packages/lint)).
- Generated filenames should match [Effective Dart Style](https://dart.dev/guides/language/effective-dart/style).

Turn something like this on for the amplify-flutter repo and codegen generated models and see what you get for warning/errors.
```yaml
include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    invalid_use_of_protected_member: error
    dead_code: info
    sdk_version_async_exported_from_core: ignore
    parameter_assignments: error
  exclude:
    # This next line will need to be uncommented to exclude the generated models.
    # - lib/models/*.dart

linter:
  rules:
    - unnecessary_statements
    - unnecessary_lambdas
    - avoid_classes_with_only_static_members
    - avoid_renaming_method_parameters
    - camel_case_types
    - constant_identifier_names
    - cascade_invocations
    - omit_local_variable_types
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - prefer_single_quotes
    - directives_ordering
    - no_default_cases
```

**Comment by Jordan-Nelson** [comment]
Hello @cto-leaps and @kjones - Thank you for your input.This is something that we are looking into.

I think this can be broken down into two issues:
1. The code generated models are not excluded from lint rules defined within the project. This is an issue since the generated models cannot possibly respect every possible lint rule that may be used within a project. To address this, the models probably need to be excluded from analysis in analysis_options.yaml.
2. The code generated models are not following dart/flutter conventions. With Flutter 2.5.0+, at least some of these conventions are now being enforced in new projects with [flutter_lints](https://github.com/flutter/packages/blob/master/packages/flutter_lints/lib/flutter.yaml). If code generated models were excluded from a projects lint rules, this wouldn't be as apparent. However, the generated models should still ideally follow conventions.

At least as a temporary workaround for those facing analysis options with generated models, the following snippet can be added to analysis_options.yaml. 
```yaml
analyzer:
  exclude:
    - "lib/models/*"
```
