### ISSUE TITLE
Flutter Web AmplifyAuthCognito SignOut not working

### ISSUE THREAD

**Issue by BerndWessels** [aws-amplify/amplify-flutter#4747]
### Description

Signing out with `AmplifyAuthCognito` `signOut()` does not sign out the current user.

Works fine on Android, but does not work on the web :(

Feels like the redirect happens before the tokens have been cleared by the plugin in the browser, but that's just a guess.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

- Build a simple Flutter Web App and add `AmplifyAuthCognito`
- Use `signInWithWebUI()` to sign in
- Use `signOut()` to sign out

User is not signed out, entries in index db are not deleted.

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  adaptive_theme: ^3.6.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  get_it: ^7.6.7
  go_router: ^13.2.2
  signals: ^5.0.0
  amplify_api: ^1.7.0
  amplify_auth_cognito: ^1.7.0
  amplify_authenticator: ^1.5.4
  amplify_flutter: ^1.7.0
  shared_preferences: ^2.2.2
  loader_overlay: ^4.0.0
  responsive_framework: ^1.4.0
  graphql: ^5.2.0-beta.7

dev_dependencies:
  flutter_test:
    sdk: flutter
```

```
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (3 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3447], locale en-NZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.88.0)
[√] Connected device (4 available)
[√] Network resources
```

### Screenshots

![image](https://github.com/aws-amplify/amplify-flutter/assets/1776695/ddd9cfdd-010d-4136-8393-79bedeaeadbd)

### Platforms

- [ ] iOS
- [ ] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.19.5

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI
