### ISSUE TITLE
amplify_auth_cognito:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by FabryPostRock** [aws-amplify/amplify-flutter#4946]
### Description

Hi everyone!

I m having big trouble in building an app with amplify libraries especially with `amplify_auth_cognito`. It's been days with 0 lines of code!

As last chance I tried to build a default flutter project but still I was not able to build with the following error:

`Could not resolve all files for configuration ':amplify_auth_cognito:androidJdkImage'.
   Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      Execution failed for JdkImageTransform: C:\Users\xxxx\AppData\Local\Android\sdk\platforms\android-33\core-for-system-modules.jar.
      C:\Users\xxxx\.gradle\caches\transforms-3\88b68384482bcb9fc6a5fd8fded5da0b\transformed\output\temp\jmod\java.base.jmod`

Below here I ll put all my sdk,jdk,pubspec,kotlin configurations:

- Android Studio Giraffe | 2022.3.1 Patch 4 and Android Studio Iguana | 2023.2.1 Patch 2. I have tried a fresh install of Iguana (deleting C:\Users\XXXX\.gradle) , but i got the same error
- Flutter 3.16.8 , Dart 3.2.5 : it's not up to date because it's the only version compatible with Unity. Moreover I tried Flutter 3.19 and 3.22 with no better results.
- JDK : 11. I have checked that the Windows JAVA_HOME environment var and the bin PATH are correctly set to this version.  In `File->Project Structure->Platform Settings ->SDKs` JDK 11 is set. In `File->Project Structure->Project Settings->Project` no SDK is set
- Android SDK BuildTools : 35-rc4
- Kotlin : 1.7.10
- Gradle : 7.5
- AGP  : 7.3.0

Laslty here is my pubspec.yaml:
```

version: 1.0.0+1

environment:
   
  sdk: '>=3.2.5 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter


application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  permission_handler: ^11.0.1
  url_launcher: ^6.2.2
  google_fonts: ^4.0.4
  flutter_dotenv: ^5.1.0
  # oauth2_client: ^2.3.2  //needs flutter_secure_storage:^5.1.2
  amplify_flutter: ^1.7.0
  amplify_core: ^1.7.0
  amplify_auth_cognito: ^1.7.0
  amplify_storage_s3: ^1.7.0
  video_player: ^2.8.6
  chewie: any
  wakelock: ^0.6.1 # Compatible version
  flutter_secure_storage: ^8.1.0 # ^5.0.2 Updated version compatible with Dart SDK
  #package_info_plus: ^5.0.1 # Compatible with flutter  3.16 Dart 3.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

dependency_overrides:
  win32: ^4.1.2
```

can you please help me find a solution?

Thank you in advance

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [X] Storage

### Steps to Reproduce

1. Create an empty Flutter project
2. Use the configuration above.

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.16, 3.22

### Amplify Flutter Version

1.7.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @FabryPostRock - I am sorry to hear you are facing this issue. This is not an error that I have see before. I have a few questions:
1. Was this working previously (with a previous version of Amplify, Flutter, Java, etc.)?
2. Does the project build if you remove amplify_auth_cognito? Does it build if you remove all amplify dependencies? 
3. Are you able to attempt to use jdk 17? A [similar issue here](https://stackoverflow.com/questions/69619829/could-not-resolve-all-files-for-configuration-appandroidjdkimage) seemed to be resolved by using jdk 17.

**Comment by FabryPostRock** [comment]
> Hello @FabryPostRock - I am sorry to hear you are facing this issue. This is not an error that I have see before. I have a few questions:
> 
> 1. Was this working previously (with a previous version of Amplify, Flutter, Java, etc.)?
> 2. Does the project build if you remove amplify_auth_cognito? Does it build if you remove all amplify dependencies?
> 3. Are you able to attempt to use jdk 17? A [similar issue here](https://stackoverflow.com/questions/69619829/could-not-resolve-all-files-for-configuration-appandroidjdkimage) seemed to be resolved by using jdk 17.

First of all thank you @Jordan-Nelson for the quick answer. It never worked for me changing to jdk 19 - 21 but i ll try in a few minutes your suggested solution with jdk 17. 

Looking at Gradle Compatibility Matrix it s not necessary to use different Gradle /AGP / Kotlin versions. I think I'll try with Gradle 7.6 , AGP 7.4 , and Kotlin 1.7.10.

**Comment by Jordan-Nelson** [comment]
@FabryPostRock Thanks for the info. Let us know if you have any luck with jdk 17 or if you are able to get the project to build without amplify dependencies.

**Comment by FabryPostRock** [comment]
> @FabryPostRock Thanks for the info. Let us know if you have any luck with jdk 17 or if you are able to get the project to build without amplify dependencies.

I have created a new default Flutter project and tried to build it first with jdk 11 without amplify packages and it worked. Then I added all amplify packages and it didn't work. Then i commented the `amplify_auth_cognito` package and it worked.

**Comment by Jordan-Nelson** [comment]
If this is a new project I would recommend using the latest version of Amplify Flutter (2.0) and to follow the platform setup guide for Android here: https://docs.amplify.aws/gen1/flutter/start/getting-started/setup/

**Comment by FabryPostRock** [comment]
> If this is a new project I would recommend using the latest version of Amplify Flutter (2.0) and to follow the platform setup guide for Android here: https://docs.amplify.aws/gen1/flutter/start/getting-started/setup/

I have created a new project with the libraries of my real current project to mess up without problems. Any suggestion about the issue?

**Comment by Jordan-Nelson** [comment]
@FabryPostRock - Maybe I misunderstood. Did you have a Flutter application with Amplify Flutter dependencies installed that was previously able to build?

**Comment by FabryPostRock** [comment]
> @FabryPostRock - Maybe I misunderstood. Did you have a Flutter application with Amplify Flutter dependencies installed that was previously able to build?

With amplify dependencies I was never able to build. I just started a default project just to work with libraries and anything else. Now I m trying version 2.0.0. Do you have any suggested sdk ,gradle , AGP , kotlin configuration for version 1.7.0?

**Comment by FabryPostRock** [comment]
Oh my god I finally made it work. Here is my configuration:

- jdk 11
- kotlin 1.7.10
- gradle 7.6
- agp 7.4.2
- flutter 3.16

pubspec.yaml:


```
version: 1.0.0+1

environment:
   
  sdk: '>=3.2.5 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter


application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  permission_handler: ^11.0.1
  url_launcher: ^6.2.2
  google_fonts: ^4.0.4
  flutter_dotenv: ^5.1.0
  # oauth2_client: ^2.3.2  //needs flutter_secure_storage:^5.1.2
  amplify_flutter: ^1.1.0
  amplify_core: ^1.1.0
  amplify_auth_cognito: ^1.1.0
  amplify_storage_s3: ^1.1.0
  video_player: ^2.8.6
  chewie: any
  wakelock: ^0.6.1 # Compatible version
  flutter_secure_storage: ^8.1.0 # ^5.0.2 Updated version compatible with Dart SDK
  #package_info_plus: ^5.0.1 # Compatible with flutter  3.16 Dart 3.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

dependency_overrides:
  win32: ^4.1.2
```

I think that the trick was to configure Amplify 1.1.0 version but I'm not sure.
