### ISSUE TITLE
Amplify Cognito Auth Module Not Found

### ISSUE THREAD

**Issue by Jukez17** [aws-amplify/amplify-flutter#5987]
I have been trying to build the flutter app to the test flight but I keep getting the `Module 'amplify_auth_cognito' not found` and I have removed the pod folder and then run `pod install`. But when I look in the symlinks folder under ios folder. Then looking at the amplify auth cognito folder, it seems that there is no ios folder at all.

Is there any reason why the ios folder is missing and is there way to resolve the issue?

**Comment by ekjotmultani** [comment]
Hi @Jukez17, could you share what your configuration and your pubspec.yaml file look like, with any credentials left out.

**Comment by Jukez17** [comment]
> Hi [@Jukez17](https://github.com/Jukez17), could you share what your configuration and your pubspec.yaml file look like, with any credentials left out.

Problem is rather interesting because i can login, register and fetch data from aws totally fine. This happens when im trying to archive to test flight

### Pubspec,yaml
```
name: test
description: "test."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.135+128

environment:
  sdk: '^3.6.1'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.5
  http: ^1.2.2
  badges: ^3.1.2
  intl: ^0.20.1
  xml: ^6.5.0
  package_info_plus: ^8.1.3
  auto_size_text: ^3.0.0
  flutter_tts: ^4.2.1
  geolocator: ^13.0.2
  background_fetch: ^1.3.7
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.2
  flutter_launcher_icons: ^0.14.3
  amplify_flutter: ^2.6.0
  amplify_core: ^2.6.0
  amplify_api: ^2.6.0
  amplify_auth_cognito: ^2.6.0
  flutter_dotenv: ^5.2.1
  #amplify_secure_storage: ^0.5.7
  audio_session: ^0.1.25

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path_android: "images/ic_launcher.png"
  image_path_ios: "images/ic_launcher.png"
  remove_alpha_ios: true
  background_color_ios: #ffffff
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/info-avatar.png
     - images/vh_logo_neg.png
     - images/ic_launcher.png
     - .env
```

### amplifyConfiguration.dart
```
const amplifyconfig = ''' {
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-central-",
              "Region": "eu-central-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-central-",
            "AppClientId": "",
            "Region": "eu-central-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "CUSTOM_AUTH",
            "OAuth": {
              "WebDomain": "[YOUR COGNITO DOMAIN ]",
              "AppClientId": "",
              "SignInRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN IN, e.g. myapp://]",
              "SignOutRedirectURI": "[CUSTOM REDIRECT SCHEME AFTER SIGN OUT, e.g. myapp://]",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            }
          }
        }
      }
    }
  }
}''';
```
