### ISSUE TITLE
I couldn't create queries with the command $ amplify codegen types or statements

### ISSUE THREAD

**Issue by yukitaka13-1110** [aws-amplify/amplify-flutter#644]
**Describe the bug**
I tried to create models by execute the following command.
```
$ amplify codegen add
```

But the following error occurred.
```
Flutter only supports the command $amplify codegen models. All the other codegen commands are not supported.
```

So I executed the indicated command and success.
Next, I tried to create queries by the following command.
```
amplify codegen statemenets
amplify codegen types
```

But both failed.
Please teach the way to create these files.

**To Reproduce**
```
amplify codegen add
amplify codegen statements
amplify codegen types
```

**Expected behavior**
Successfully created queries.

**Screenshots**
No screenshots

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
- [x] Android
- [x] iOS
- [x] Flutter

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  Flutter only supports the command $amplify codegen models. All the other codegen commands are not supported.

</details>

**Smartphone (please complete the following information):**
 - Device: No device
 - OS: -
 - Flutter 2.2.0

**Additional context**
```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^0.2.0-nullsafety.0
  amplify_api: ^0.2.0-nullsafety.0
```
