### ISSUE TITLE
Cognito Auth - FetchAuthSession Reports 'User Signed In' In Even Though The Tokens Are Invalid

### ISSUE THREAD

**Issue by genjm** [aws-amplify/amplify-flutter#835]
When I launch my application, it uses Amplify.Auth.fetchAuthSession() to check if the user is signed in / has a valid session.

Via the output, I can see that this fails due to 'Tokens are invalid, please sign-in again' within the AWSMobileClient code.

It retries twice & then reports the user as signed in correctly, at which point my application then tries to get the user attributes, which fails as the user is not actually signed in.

Log as follows:

`
Restarted application in 1,928ms.
I/flutter (11018): Successfully configured Amplify 🎉

D/AWSMobileClient(11018): Inspecting user state details
W/AWSMobileClient(11018): signalTokensNotAvailable
W/AWSMobileClient(11018): Tokens are invalid, please sign-in again.
W/AWSMobileClient(11018): signalTokensNotAvailable
D/AWSMobileClient(11018): Inspecting user state details
W/AWSMobileClient(11018): signalTokensNotAvailable
W/AWSMobileClient(11018): Tokens are invalid, please sign-in again.
D/AWSMobileClient(11018): waitForSignIn: userState:SIGNED_IN
D/AWSMobileClient(11018): getCredentials: Validated user is signed-in

D/AWSMobileClient(11018): Inspecting user state details
W/AWSMobileClient(11018): signalTokensNotAvailable
W/AWSMobileClient(11018): Tokens are invalid, please sign-in again.
D/AWSMobileClient(11018): waitForSignIn: userState:SIGNED_IN

E/amplify:flutter:auth_cognito(11018): AuthException
I/flutter (11018): AuthException(message: Fetching user attributes failed., recoverySuggestion: See attached exception for more details., underlyingException: com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoInternalErrorException: Failed to authenticate user)`

As you can see, the only time I get an exception returned to my code is when the fetchUserAttributes() call fails.

Why does it report the user as signed in after it has failed three times, surely it should be reporting the user as not signed in so that the application can handle this correctly?

**Comment by offlineprogrammer** [comment]
Hey @genjm 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo

**Comment by Miamoto-Musashi** [comment]
same problem here

```bash
W/AWSMobileClient( 5937): signalTokensNotAvailable
W/AWSMobileClient( 5937): Tokens are invalid, please sign-in again.
W/AWSMobileClient( 5937): java.lang.Exception: No cached session.
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient$12$1.signalTokensNotAvailable(AWSMobileClient.java:2021)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient$12$1.getAuthenticationDetails(AWSMobileClient.java:2001)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1035)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient$12.run(AWSMobileClient.java:1982)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1948)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1097)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:976)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.AWSMobileClient$21.run(AWSMobileClient.java:2699)
W/AWSMobileClient( 5937): 	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/AWSMobileClient( 5937): 	at java.lang.Thread.run(Thread.java:923)
D/AWSMobileClient( 5937): waitForSignIn: userState:SIGNED_OUT_USER_POOLS_TOKENS_INVALID
W/CognitoUserSession( 5937): CognitoUserSession is not valid because idToken is null.
W/AWSMobileClient( 5937): signalTokensNotAvailable
```

my pubspec.yml

```yaml
name: customer
description: >-
  Here at Truxy We help Logistic Managers find a relaibale truck in less than 3 minutes on our vetted network.
version: 1.0.0+2
homepage: https://truxy.io
documentation: https://truxy.io/docs
publish_to: none
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  amplify_auth_cognito: ^0.5.1
  amplify_datastore: ^0.5.1
  amplify_flutter: ^0.5.1
  amplify_api: ^0.5.1
  amplify_storage_s3: ^0.5.1

  calendar_timeline: 1.0.4
  colorize_lumberdash: ^3.0.0
  country_icons: 2.0.2
  cupertino_icons: ^1.0.4
  dart_countries_states: 0.1.1
  flutter:
    sdk: flutter
  flutter_google_places: 0.3.0
  flutter_localizations:
    sdk: flutter
  # amplify_authenticator: ^0.1.0
  flutter_login: 3.2.0
  flutter_multi_formatter: 2.5.7
  flutter_typeahead: 3.2.4
  get: 4.6.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  line_icons: ^2.0.1
  multi_select_flutter: ^4.1.2
  sentry_lumberdash: ^3.2.0
  syncfusion_flutter_sliders: 20.1.57
  time_range_picker: 2.1.0
  path_provider: ^2.0.10

dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.1
  mockito: 5.2.0
  flutter_launcher_icons_maker: ^0.10.2



flutter:
  uses-material-design: true
  assets:
    - assets/images/white_logo.png
    - assets/images/cyan_logo.png

flutter_intl:
  localizely:
    project_id: 24cafcb8-b078-4670-9e75-2cebaa48a839
  enabled: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/white_logo.png

```
