### ISSUE TITLE
iOS: Fatal error: Unexpectedly found nil while unwrapping an Optional value: file Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift, line 211

### ISSUE THREAD

**Issue by danielvtan** [aws-amplify/amplify-flutter#88]
**Describe the bug**
iOS app crash when logging in

**Expected behavior**
Should be able to login

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducable in (check all that apply):
[] Android
[X] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone 8 
 - OS: iOS 13.3

**Additional context**
```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file 
<project location>Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift, line 211
```
Same project run in android is working
```
dependencies:
...
  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
````

```const amplifyconfig = ''' {
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "ap-southeast-1:---",
                            "Region": "ap-southeast-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-1_---",
                        "AppClientId": "---",
                        "AppClientSecret": "---",
                        "Region": "ap-southeast-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}''';
```

**Comment by danielvtan** [comment]
Issue was. we had a third party flutter cognito plugin installed. removing it resolved the issue

**Comment by pal** [comment]
I get this same error in iOS and only have these deps:
```
dependencies:
  flutter:
    sdk: flutter

  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
```

This is the stock todo-app, but with the addition of sign-in code:
```dart
SignInResult res = await Amplify.Auth.signIn(
  username: 'myusername',
  password: 'mysupersecurepassword',
);
```

Any ideas?
