### ISSUE TITLE
A problem occurred evaluating root project 'amplify_auth_cognito'.

### ISSUE THREAD

**Issue by ADLsourceCode** [aws-amplify/amplify-flutter#890]
Hi,

Getting the below error while building the Flutter app, Everything worked fine till yesterday...

```



FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':amplify_auth_cognito:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':amplify_auth_cognito:debugRuntimeClasspath'.
   > Could not resolve androidx.navigation:navigation-runtime:[2.3.2].
     Required by:
         project :amplify_auth_cognito > project :amplify_core > com.amplifyframework:core:1.16.13 > androidx.navigation:navigation-fragment:2.3.2
         project :amplify_auth_cognito > project :amplify_core > com.amplifyframework:core:1.16.13 > androidx.navigation:navigation-ui:2.3.2
         project :amplify_auth_cognito > project :amplify_core > com.amplifyframework:core:1.16.13 > androidx.navigation:navigation-fragment-ktx:2.3.2 > androidx.navigation:navigation-runtime-ktx:2.3.2
      > Failed to list versions for androidx.navigation:navigation-runtime.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/androidx/navigation/navigation-runtime/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/androidx/navigation/navigation-runtime/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/androidx/navigation/navigation-runtime/maven-metadata.xml'.
                  > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin amplify_auth_cognito...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/akshay/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_auth_cognito-0.1.0/android/build.gradle' line: 62

* What went wrong:
A problem occurred evaluating root project 'amplify_auth_cognito'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().
  
  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin amplify_auth_cognito could not be built due to the issue above.
```

**Below is my Project Gradle**

```
`buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.2.0'
//        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`
```

**Pubspec.yaml file** 
```

name: telemed
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: 3.1.0
  splashscreen: ^1.2.0
  open_iconic_flutter: ^0.3.0
  progress_dialog: ^1.2.4
  connectivity: ^0.4.9
  percent_indicator: "^2.1.5"
  geolocator:
  toast: ^0.1.5
  argon_buttons_flutter: ^1.0.6
  carousel_slider: ^1.4.1
  calendar_strip: ^1.0.4
  flutter_animated_dialog: ^1.1.0
  flutter_share_me: ^0.9.1
  flutter_spinkit: "^4.1.2"
  google_maps_flutter: ^0.5.33
  cool_stepper: ^1.1.0
  modal_progress_hud: ^0.1.3
  image_picker: ^0.6.7+7
  photo: 0.4.8
  titled_navigation_bar: ^4.1.0
  giffy_dialog: ^1.8.0
  grouped_list: ^3.3.0
  carousel_pro: ^1.0.0
  uuid: 2.2.2
  flutter_webview_plugin: ^0.3.10+1
  awesome_dialog: ^1.2.0
  google_fonts: ^1.1.0
  responsive_navigation_bar: ^1.2.0+1
  data_connection_checker: ^0.3.4
  hawk_fab_menu: ^0.3.2
  date_time_picker: ^1.0.1
  date_format: ^1.0.9
  avatar_glow: ^1.2.0
  fa_stepper: ^0.0.1
  path_provider: ^1.6.14
  share: ^0.6.5
  page_slider: ^0.0.2
  email_validator: ^1.0.0
  intl:
  form_validator: ">=0.1.1 <2.0.0"
  sortedmap: ^0.4.2+1
  font_awesome_flutter: ^8.10.0
  permission_handler: 5.0.1+1
  octo_image: ^0.3.0
  cached_network_image: ^2.0.0
  qr_flutter: ^3.2.0
  amplify_core: '<1.0.0'

  http:
  amplify_flutter: <1.0.0
  amplify_auth_cognito: '<1.0.0'
  amplify_storage_s3: '<1.0.0'
  carousel_indicator: ^1.0.5
  qrcode:
  url_launcher:
  geocoding:
#  flappy_search_bar:
  material_floating_search_bar:
  autocomplete_textfield: ^1.7.3
  firebase_storage: ^3.0.3
  firebase_messaging: ^5.0.2
  firebase_core: ^0.4.5
  cloud_firestore: 0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/Images/loginbg.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
